// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJzZy5rLjXgLa5lHaEVUqx8QpJtAOAhpY',
    appId: '1:931769459436:web:170349ee03fdd6c97f7bc9',
    messagingSenderId: '931769459436',
    projectId: 'emo-sik',
    authDomain: 'emo-sik.firebaseapp.com',
    databaseURL: 'https://emo-sik-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emo-sik.firebasestorage.app',
    measurementId: 'G-8MYDSMWKTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvX8Yod0cwkLXGiu7oFensbixCZIPK1mk',
    appId: '1:931769459436:android:be21923d8903b2c87f7bc9',
    messagingSenderId: '931769459436',
    projectId: 'emo-sik',
    databaseURL: 'https://emo-sik-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emo-sik.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgO00cyRrvcbshk8ocJOXx9hIdRpPJDMU',
    appId: '1:931769459436:ios:7a0fa1d35662a1957f7bc9',
    messagingSenderId: '931769459436',
    projectId: 'emo-sik',
    databaseURL: 'https://emo-sik-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emo-sik.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgO00cyRrvcbshk8ocJOXx9hIdRpPJDMU',
    appId: '1:931769459436:ios:7a0fa1d35662a1957f7bc9',
    messagingSenderId: '931769459436',
    projectId: 'emo-sik',
    databaseURL: 'https://emo-sik-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emo-sik.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJzZy5rLjXgLa5lHaEVUqx8QpJtAOAhpY',
    appId: '1:931769459436:web:cc3bfdc0e66188307f7bc9',
    messagingSenderId: '931769459436',
    projectId: 'emo-sik',
    authDomain: 'emo-sik.firebaseapp.com',
    databaseURL: 'https://emo-sik-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emo-sik.firebasestorage.app',
    measurementId: 'G-EXBYZLBYHM',
  );
}
