// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF8qtXAUYV-Jv1grFOzzUkZodTcoABo-Q',
    appId: '1:49141182150:web:004184dcb90a2cedb5b1c7',
    messagingSenderId: '49141182150',
    projectId: 'exploremoris-f35df',
    authDomain: 'exploremoris-f35df.firebaseapp.com',
    storageBucket: 'exploremoris-f35df.firebasestorage.app',
    measurementId: 'G-HLNGPLZ140',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6wPg8K5XbS_TWheP0DTxnWQo8z1SVf50',
    appId: '1:49141182150:android:21604d1b7a0fac6eb5b1c7',
    messagingSenderId: '49141182150',
    projectId: 'exploremoris-f35df',
    storageBucket: 'exploremoris-f35df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt0-6R7PLSNQVxsWca9YfKQhxSQM_RrGs',
    appId: '1:49141182150:ios:e27b13f7f52db904b5b1c7',
    messagingSenderId: '49141182150',
    projectId: 'exploremoris-f35df',
    storageBucket: 'exploremoris-f35df.firebasestorage.app',
    iosBundleId: 'com.example.exploreMoris',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt0-6R7PLSNQVxsWca9YfKQhxSQM_RrGs',
    appId: '1:49141182150:ios:e27b13f7f52db904b5b1c7',
    messagingSenderId: '49141182150',
    projectId: 'exploremoris-f35df',
    storageBucket: 'exploremoris-f35df.firebasestorage.app',
    iosBundleId: 'com.example.exploreMoris',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF8qtXAUYV-Jv1grFOzzUkZodTcoABo-Q',
    appId: '1:49141182150:web:9a3fa531ebc3febfb5b1c7',
    messagingSenderId: '49141182150',
    projectId: 'exploremoris-f35df',
    authDomain: 'exploremoris-f35df.firebaseapp.com',
    storageBucket: 'exploremoris-f35df.firebasestorage.app',
    measurementId: 'G-C0Z857EPLV',
  );
}
